### ISSUE TITLE
For `gmatch`, the an initial "^" is not magic.

### ISSUE THREAD

**Issue by pygy** [pygy/strung.lua#10]
```Lua
for m in strung.gmatch("a", "^a") do 
    print(m)
end
```
... should not print anything.

```Lua
for m in strung.gmatch("^a", "^a") do 
    print(m)
end
```
... should print `"^a"`.

Currently, they print `"a"` and nothing, respectively.

**Comment by CapsAdmin** [comment]
If you don't use round brackets it defaults to `(^a)`  and not `^(a)`? This seems like odd behavior on Lua's part.

**Comment by pygy** [comment]
Actually, the initial "^" isn't treated as a metacharacter...

**Comment by pygy** [comment]
Fixed :-)
